### ISSUE TITLE
Beschrijf je functies ietjes beter

### ISSUE THREAD

**Issue by heralt** [randy554/web-app-from-scratch-1920#2]
https://github.com/randy554/web-app-from-scratch-1920/blob/450af59e1e8e83e4d7b5d4da857d7e3ed42f95ee/docs/js/main.js#L10

Beschrijf wat je functies doen en wat je parameter is. Dat kan je doen met dit:
```js
/**
 *
 * @param data
 */

**Comment by randy554** [comment]
Heb alle functies voorzien van comments en parameters namen gegeven die de inhoud beter omschrijven.
